---
version: "3.3"

services:
  web_nginx:
    image: nginx:1.20-alpine
    container_name: front-nginx
    depends_on:
      - php_fpm
    restart: always
    ports:
      - "80:80" #http
      - "443:443" #https
    volumes:
      - ./www:/www
      - ./docker-data/nginx/config:/etc/common
      - ./docker-data/nginx/config/main.conf:/etc/nginx/conf.d/main.conf
    links:
      - php_fpm
      - phpmyadmin
    networks:
      - wmnet

  php_fpm:
    image: php:7.4-fpm
    container_name: php7.4-fpm
    restart: always
    volumes:
      - ./www:/www
      - ./docker-data/php/config/php.ini:/usr/local/etc/php/conf.d/php.ini
    command:
      - /bin/sh
      - -cx
      - |
        docker-php-ext-install mysqli
        php-fpm
    networks:
      - wmnet

  database_service:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker-data/mysql/dump:/dump
      - ./docker-data/mysql/mysql-data:/var/lib/mysql
      - ./docker-data/mysql/config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: mysql_db
      MYSQL_USER: user@1
      MYSQL_PASSWORD: 123
    networks:
      - wmnet

  phpmyadmin:
    #    image: phpmyadmin/phpmyadmin:5.2
    build: ./dockerfiles/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - database_service
    ports:
      - "5501:80"
    environment:
      PMA_HOST: database_service
      UPLOAD_LIMIT: 5G
      MEMORY_LIMIT: 1024M
      MAX_EXECUTION_TIME: 900
      PHP_UPLOAD_MAX_FILESIZE: 5G
      PHP_MAX_INPUT_VARS: 10000
    networks:
      - wmnet
networks:
  wmnet:
...